name: build_mate
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.0.5
  supabase: ^1.9.5
  supabase_flutter: ^1.10.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib\assets\landing_illu.png
    - lib\assets\Logo.png
    - lib\assets\Login.png
